name: dorak_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7+1
  animate_do: ^4.2.0
  local_auth: ^2.3.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  pinput: ^5.0.1
  intl_phone_field: ^3.2.0
  equatable: ^2.0.7
  flutter_slidable: ^4.0.0
  flutter_launcher_icons: ^0.14.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/
    - assets/font/
    - assets/translations/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_app.png"
