// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi3dVVe491KMegztTleXxb4obCJifi-r0',
    appId: '1:1089688238370:web:869e7087cd9f155058cd7b',
    messagingSenderId: '1089688238370',
    projectId: 'dorak-app-27186',
    authDomain: 'dorak-app-27186.firebaseapp.com',
    storageBucket: 'dorak-app-27186.firebasestorage.app',
    measurementId: 'G-ZXDEG6545E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM0QLOOhSMRRQTyoPPHWDs7j4pKVYzDqA',
    appId: '1:1089688238370:android:11dcdb6856684f7b58cd7b',
    messagingSenderId: '1089688238370',
    projectId: 'dorak-app-27186',
    storageBucket: 'dorak-app-27186.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiJVseC8SOvjVxHLXXuhsGyNqD4qS-C-0',
    appId: '1:1089688238370:ios:b7e5d641bb48bea258cd7b',
    messagingSenderId: '1089688238370',
    projectId: 'dorak-app-27186',
    storageBucket: 'dorak-app-27186.firebasestorage.app',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiJVseC8SOvjVxHLXXuhsGyNqD4qS-C-0',
    appId: '1:1089688238370:ios:b7e5d641bb48bea258cd7b',
    messagingSenderId: '1089688238370',
    projectId: 'dorak-app-27186',
    storageBucket: 'dorak-app-27186.firebasestorage.app',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi3dVVe491KMegztTleXxb4obCJifi-r0',
    appId: '1:1089688238370:web:fb082bdfa5dfe51558cd7b',
    messagingSenderId: '1089688238370',
    projectId: 'dorak-app-27186',
    authDomain: 'dorak-app-27186.firebaseapp.com',
    storageBucket: 'dorak-app-27186.firebasestorage.app',
    measurementId: 'G-L6TEH95M0L',
  );
}
